chore: add database access, moved mocks from controllers to db
FromDoppler/doppler-reporting-api pull request #4
Opened 2021-09-28 12:01 UTC by aferraromedina

Fixes:  Jira Ticket, ie. [DW-1167](https://makingsense.atlassian.net/browse/DW-1167) 

### Checklist:

- [x] I have paid attention to this PR title and description
- [x] I have performed a self-review of my code
- [x] I have built it locally (or my changes does not affect the build)
- [ ] I have checked all tests still run ok at Doppler.ReportingApiTest project
- [ ] I have added at least one simple unit test covering the new code

2021-09-29 17:52 UTC, javierburger commented on Doppler.ReportingApi/Controllers/SummaryController.cs
>          public async Task<CampaignsSummary> Campaigns(string accountName, [FromQuery] BasicDatefilter dateFilter)
No se si es una convencion, pero en los nombres de los metodos especificamos que hace, por ejemplo GetCampaignsSummary o algo asi

2021-09-29 19:35 UTC, javierburger commented on Doppler.ReportingApi/Infrastructure/SummaryRepository.cs
> +                var dummyDatabaseQuery = @"SELECT 1000 as TotalSubscribers, 750 as NewSubscribers, 80 as RemovedSubscribers";
pense que ya estaba implementado pegandole a la DB

2021-09-29 19:49 UTC, aferraromedina commented on Doppler.ReportingApi/Infrastructure/SummaryRepository.cs
> +                var dummyDatabaseQuery = @"SELECT 1000 as TotalSubscribers, 750 as NewSubscribers, 80 as RemovedSubscribers";
🤦‍♂️ falto el push.

2021-09-29 20:43 UTC, aferraromedina commented on Doppler.ReportingApi/Controllers/SummaryController.cs
>          public async Task<CampaignsSummary> Campaigns(string accountName, [FromQuery] BasicDatefilter dateFilter)
✔

2021-09-30 13:11 UTC, MarianoHerrera requested changes

2021-09-30 13:11 UTC, MarianoHerrera commented on Doppler.ReportingApi/Controllers/SummaryController.cs
> +            var endDate = dateFilter.EndDate;
Tal vez en la ignorancia de como funciona el controlador, pero si estamos suponiendo que la fecha de comienzo puede no ser provista, seria correcto pensar que la fecha de finalizacion siempre va a ser declarada?

2021-09-30 13:11 UTC, MarianoHerrera commented on Doppler.ReportingApi/Infrastructure/SummaryRepository.cs
> +                    ) T";
Aca se está teniendo en cuenta campañas de automation y de test, supongo que las de test deberian de ignorarse y las de automation calcularse de una manera distinta si es que aplica que se retorne el total de enviados.
Para una cuenta con campañas grandes enviadas esto tambien puede traer problemas de performance ya que contar todas las campañas de un usuario si el rango de fechas es amplio puede ser costoso. Una alternativa podria ser utilizar las columnas en la tabla campaign que se alimentan con triggers de la tabla campaigndeliveriesopeninfo. Estos nros en general son exactos, pero suceden deadlocks que terminan desfazando el valor total real del que está calculado en la columna. Depende de el propósito del que se necesite estos totales, si no es para facturación, tal vez se puedan utilizar, habria que analizar que tanto error hay en estas columnas.

2021-09-30 13:11 UTC, MarianoHerrera commented on Doppler.ReportingApi/Infrastructure/SummaryRepository.cs
> +                    (SELECT Count(1) FROM Subscriber S INNER JOIN [User] on [User].idUser = S.IdUser  WHERE [User].Email = @userName) AS TotalSubscribers,
aca se puede utilizar una vista que ya tiene el total calculado por cuenta.
```suggestion
                    (SELECT SUM(v.Amount) FROM [dbo].[ViewSubscribersByStatusXUserAmount] V INNER JOIN [User] on [User].idUser = V.IdUser  WHERE [User].Email = @userName) AS TotalSubscribers,
```

2021-09-30 13:49 UTC, andresmoschini commented on Doppler.ReportingApi/Controllers/SummaryController.cs
> +            var endDate = dateFilter.EndDate;
Creo que en el caso de `startDate` si no tiene valor se asume 30 días en el pasado. Respecto a `endDate` supongo que si no tiene valor no se filtra. 

@aferraromedina podrás confirmar?

2021-09-30 13:50 UTC, andresmoschini commented on Doppler.ReportingApi/Controllers/SummaryController.cs
>          public async Task<SubscribersSummary> Subscribers(string accountName, [FromQuery] BasicDatefilter dateFilter)
No se si entra en el scope de este PR, pero estaría bien renombrar este método como `GetSubscribers`, no?

2021-09-30 13:59 UTC, andresmoschini commented on Doppler.ReportingApi/Models/BasicDatefilter.cs
> +        public DateTime EndDate { get; set; } = DateTime.Today;
Osea las 0 horas del día de hoy?

2021-09-30 13:59 UTC, andresmoschini commented on Doppler.ReportingApi/Models/BasicDatefilter.cs
> +        public DateTime EndDate { get; set; } = DateTime.Today;
Creo que deberías usar DateTiemeOffset para todo lo que sea comunicación de la API para afuera.

Luego, por dentro del sistema podés usar DateTime asumiento UTC

2021-09-30 14:01 UTC, MarianoHerrera commented on Doppler.ReportingApi/Infrastructure/SummaryRepository.cs
> +                    ) T";
Ahi realice unos reportes y desde el 1ro de enero hasta la fecha hubo 11 campañas con diferencias, que nos da un 0.0045199783041041% de error, y de esas 11 veo que se han tocado a mano algunas, con lo cual el error es menor.

2021-10-04 21:28 UTC, aferraromedina commented on Doppler.ReportingApi/Controllers/SummaryController.cs
> +            var endDate = dateFilter.EndDate;
@MarianoHerrera tenes razon, esta mal que asuma una y no la otra, la idea del rango es acotar la query a la db.  muy buena observacion :)
@andresmoschini exacto, endDate si no tiene valor asumia por defecto la fecha de hoy, pero esta mal porque si consultas con una fecha muy vieja rompes el objetivo del filtro.

2021-10-04 21:32 UTC, aferraromedina commented on Doppler.ReportingApi/Infrastructure/SummaryRepository.cs
> +                    ) T";
@MarianoHerrera Modifique para utilizar las columnas que mencionaste, por el momento no hay un requerimiento de que la informacion sea 100% perfecta. por ahora limitamos a 30 dias la consulta, a futuro (todavia nadie consume esta api) vamos a agregar algun esquema de cache para disminuir las consultas a la db

2021-10-04 21:32 UTC, aferraromedina commented on Doppler.ReportingApi/Infrastructure/SummaryRepository.cs
> +                    (SELECT Count(1) FROM Subscriber S INNER JOIN [User] on [User].idUser = S.IdUser  WHERE [User].Email = @userName) AS TotalSubscribers,
Cambiado ✔

2021-10-04 21:34 UTC, aferraromedina commented on Doppler.ReportingApi/Controllers/SummaryController.cs
>          public async Task<SubscribersSummary> Subscribers(string accountName, [FromQuery] BasicDatefilter dateFilter)
Lo tomo de todas formas :)

2021-10-04 21:35 UTC, aferraromedina commented on Doppler.ReportingApi/Models/BasicDatefilter.cs
> +        public DateTime EndDate { get; set; } = DateTime.Today;
no estaba del todo bien esto.

2021-10-04 21:35 UTC, aferraromedina commented on Doppler.ReportingApi/Models/BasicDatefilter.cs
> +        public DateTime EndDate { get; set; } = DateTime.Today;
✔

2021-10-05 11:51 UTC, MarianoHerrera commented on Doppler.ReportingApi/Infrastructure/SummaryRepository.cs
> +                ) T";
Aca faltó ignorar las campañas de test no? seria IdTestCampaign IS NULL en la tabla campaign, y no se en que quedo el tema de automation. Tenemos automations que quedan "vivos" y se va actualizando el UTCSentDate, entonces en la query como está ahora va a retornar que para una fecha envio X cantidad pero puede estar tomando en cuenta un automation que solo hizo un solo envio y el resto fuera de el rango de fechas.

2021-10-07 15:24 UTC, andresmoschini commented on Doppler.ReportingApi/Models/BasicDatefilter.cs
> +        public DateTime EndDate { get; set; } = DateTime.Today;
@aferraromedina ya quitó toda la generación automática de los valores de fecha, ahora son requeridos.

Marco conversación como resuelta.

2021-11-26 13:46 UTC, merged